services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - "services/catalog/.env"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app_catalog:
    build:
      context: .
      dockerfile: services/catalog/Dockerfile
    command: [ "sh", "-c", "alembic -c services/catalog/migrations/alembic.ini upgrade head && uvicorn services.catalog.main:app --host 0.0.0.0 --port 8000" ]
    env_file:
      - services/catalog/.env
    ports:
      - "8000:8000"
    depends_on:
      db_catalog:
        condition: service_healthy

  db_catalog:
    image: postgres:16-alpine
    env_file: services/catalog/.env
    environment:
      POSTGRES_USER: catalog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog"]
      interval: 5s
      timeout: 5s
      retries: 10

  celery_worker:
    build:
      context: .
      dockerfile: services/catalog/Dockerfile
    command: celery -A services.catalog.celery worker -l info --include=services.catalog.tasks
    env_file:
      - services/catalog/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

#  api:
#    build: .
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    environment:
#      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    restart: unless-stopped

#  bot:
#    build: .
#    command: ["python", "-m", "notification"]
#    env_file:
#      - .env
#    environment:
#      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    restart: unless-stopped


volumes:
  pgdata:
  minio_data: